### Obtenemos lineas de la factura
POST http://localhost:3000/obtenerFacturaLineas HTTP/1.1
Content-Type: application/json


  {
  "empresaCod": "EM002",
  "serieCod": "S002",
  "facturaVentaNum": "1"

  }

### Agregamos linea a la factura
POST http://localhost:3000/agregarFacturaLinea HTTP/1.1
Content-Type: application/json


  {
  "empresaCod": "EM002",
  "serieCod": "S002",
  "facturaVentaNum": "1"

  }

### Rellenar factura linea
POST http://localhost:3000/rellenarFacturaLinea HTTP/1.1
Content-Type: application/json

{"lineaFactura":
  {
  "empresaCod": "EM002",
  "serieCod": "S002",
  "facturaVentaNum": "1",
  "facturaVentaLineaNum": "3",
  "proyectoCod": "PR002",
  "texto": "Línea de factura 2",
  "cantidad": 6,
  "precio": 50,
  "importeBruto": 300,
  "descuento": 0,
  "tipoIVACod": "IVA4",
  "tipoIRPFCod": "IRPF37"
  }
}

### Obtenemos cuotas de la factura
POST http://localhost:3000/obtenerDatosFinalesFactura HTTP/1.1
Content-Type: application/json


  {
  "empresaCod": "EM002",
  "serieCod": "S002",
  "facturaVentaNum": "1"

  }