POST http://localhost:3000/agregarFactura HTTP/1.1
Content-Type: application/json

{"factura":{
  "empresaCod": "EM002",
  "serieCod": "S002",
  "facturaVentaNum":"12",
  "clienteCod": "CL002",
  "fechaEmision": "2024-06-30"
}
}